version: "4.3"

services:
  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app 
      - /usr/src/app/node_modules 

    develop:
      watch:
        - path: ./frontend
          target: /usr/src/app
          action: sync
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
    develop:
      watch:
        - path: ./backend
          target: /usr/src/app
          action: sync
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://db:27017/loganalyzer
    restart: unless-stopped

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongodb_data:
